<?php

namespace AppBundle\Repository;

/**
 * Currency
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Currency extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return null|array
     */
    public function getAllCurrencies()
    {
        return $this->findAll();
    }
}
