<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity;

/**
 * ExchangeRate
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRate extends EntityRepository
{
    /**
     * @param $date
     * @return null|array
     */
    public function getExchangeRatesByDate($date)
    {
        return $this->findBy(array('date' => $date));
    }

    /**
     * @param Entity\ExchangeRate $exchangeRateEntity
     */
    public function saveExchangeRate(Entity\ExchangeRate $exchangeRateEntity)
    {
        $this->_em->persist($exchangeRateEntity);
        $this->_em->flush();
    }
}
