# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    mail_helper:
        class: AppBundle\Util\MailHelper
        arguments: ['@mailer']
    app.form.type.datepicker:
        class: AppBundle\Form\Type\DateFormType
        arguments: [AppBundle\Entity\ExchangeRate]
        tags:
            - { name: form.type, alias: datepicker }